name: indra
version: 0.2.0
description: Scriptable integration and automation engine
homepage: https://github.com/stijnvanbael/indra

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  shelf: ^1.4.1
  yaml: ^3.1.1
  ansicolor: ^2.0.1
  http: ^0.13.5
  webdriver: ^3.0.2
  yaml_edit: ^2.1.0
