name: indra
version: 0.0.1
description: Hackable integration and automation engine

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  shelf: ^0.7.3
  yaml: ^2.1.15
  meta: ^1.1.6
  ansicolor: ^1.0.2
  http: 0.12.0+2
